vich_uploader:
    db_driver: orm

    mappings:
        file_message:
            uri_prefix: /upload
            upload_destination: '%kernel.project_dir%/public/upload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true